/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rent;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author abdelrahman
 */
public class ajout_voiture extends javax.swing.JFrame {

    /**
     * Creates new form ajout_voiture
     */
    public ajout_voiture() {
        initComponents();
        Dimension dim=getToolkit().getScreenSize();
        this.setSize(dim);
       marque.setBackground(new java.awt.Color(0,0,0,1));
       model.setBackground(new java.awt.Color(0,0,0,1));
       c_voiture.setBackground(new java.awt.Color(0,0,0,1));
       n_voiture.setBackground(new java.awt.Color(0,0,0,1));
       killo.setBackground(new java.awt.Color(0,0,0,1));
       annee.setBackground(new java.awt.Color(0,0,0,1));
       couleur.setBackground(new java.awt.Color(0,0,0,1));
       nb_place.setBackground(new java.awt.Color(0,0,0,1));
       nb_porte.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton3 = new javax.swing.JButton();
        marque = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        model = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        c_voiture = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n_voiture = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        killo = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        annee = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        couleur = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nb_place = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        nb_porte = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        type_voiture = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        type_boite = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        type_energie = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 255));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_car_50px.png"))); // NOI18N
        jButton3.setText("MARQUE");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        marque.setBackground(new java.awt.Color(255, 255, 255));
        marque.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        marque.setForeground(new java.awt.Color(0, 0, 0));
        marque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marque.setBorder(null);
        marque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                marqueFocusGained(evt);
            }
        });
        marque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marqueActionPerformed(evt);
            }
        });

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator22.setForeground(new java.awt.Color(0, 0, 0));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_steering_wheel_50px.png"))); // NOI18N
        jButton4.setText("MODELE");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        model.setBackground(new java.awt.Color(255, 255, 255));
        model.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        model.setForeground(new java.awt.Color(0, 0, 0));
        model.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        model.setBorder(null);
        model.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modelFocusGained(evt);
            }
        });
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));

        c_voiture.setBackground(new java.awt.Color(255, 255, 255));
        c_voiture.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        c_voiture.setForeground(new java.awt.Color(0, 0, 0));
        c_voiture.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_voiture.setBorder(null);
        c_voiture.setEnabled(false);
        c_voiture.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c_voitureFocusGained(evt);
            }
        });
        c_voiture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_voitureActionPerformed(evt);
            }
        });

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CODE VOITURE");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("N° VOITURE");

        n_voiture.setBackground(new java.awt.Color(255, 255, 255));
        n_voiture.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        n_voiture.setForeground(new java.awt.Color(0, 0, 0));
        n_voiture.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        n_voiture.setBorder(null);
        n_voiture.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n_voitureFocusGained(evt);
            }
        });
        n_voiture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_voitureActionPerformed(evt);
            }
        });

        jSeparator25.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("KILLOMETRAGE");

        killo.setBackground(new java.awt.Color(255, 255, 255));
        killo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        killo.setForeground(new java.awt.Color(0, 0, 0));
        killo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        killo.setBorder(null);
        killo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                killoFocusGained(evt);
            }
        });
        killo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                killoActionPerformed(evt);
            }
        });

        jSeparator26.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator26.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ANNEE");

        annee.setBackground(new java.awt.Color(255, 255, 255));
        annee.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        annee.setForeground(new java.awt.Color(0, 0, 0));
        annee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        annee.setBorder(null);
        annee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                anneeFocusGained(evt);
            }
        });
        annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneeActionPerformed(evt);
            }
        });

        jSeparator27.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator27.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("COULEUR");

        couleur.setBackground(new java.awt.Color(255, 255, 255));
        couleur.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        couleur.setForeground(new java.awt.Color(0, 0, 0));
        couleur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        couleur.setBorder(null);
        couleur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                couleurFocusGained(evt);
            }
        });
        couleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couleurActionPerformed(evt);
            }
        });

        jSeparator28.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_RGB_Color_Wheel_20px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NB.PLACES");

        nb_place.setBackground(new java.awt.Color(255, 255, 255));
        nb_place.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        nb_place.setForeground(new java.awt.Color(0, 0, 0));
        nb_place.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nb_place.setBorder(null);
        nb_place.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nb_placeFocusGained(evt);
            }
        });
        nb_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb_placeActionPerformed(evt);
            }
        });

        jSeparator29.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NB.PORTES");

        nb_porte.setBackground(new java.awt.Color(255, 255, 255));
        nb_porte.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        nb_porte.setForeground(new java.awt.Color(0, 0, 0));
        nb_porte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nb_porte.setBorder(null);
        nb_porte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nb_porteFocusGained(evt);
            }
        });
        nb_porte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb_porteActionPerformed(evt);
            }
        });

        jSeparator30.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator30.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("TYPE VOITURE");

        type_voiture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECTIONNEZ TYPE DE VOITURE", "SUV", "SPORT", "4X4", "COUPE", "CABRIOLET", "UTILITAIRE" }));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TYPE BOITE");

        type_boite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECTIONNEZ TYPE DE BOITE", "AUTOMATIQUE", "MANUELLE" }));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("TYPE ENERGIE");

        type_energie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECTIONNEZ TYPE D'ENERGIE ", "DIESEL", "ESSENCE", "ELECTRIQUE" }));

        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("AJOUT VOITURE");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_save_50px.png"))); // NOI18N
        jButton2.setText("ENREGISTER");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(153, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Login_50px.png"))); // NOI18N
        jButton5.setText("RETOUR");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dungeon", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Car_Rental_40px.png"))); // NOI18N
        jLabel12.setText("   CAR-LOCO");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(type_voiture, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(marque, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(jSeparator22))
                                        .addGap(151, 151, 151)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(type_boite, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel6))
                                                .addGap(28, 28, 28)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(c_voiture)
                                                        .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(killo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(42, 42, 42)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(33, 33, 33)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(n_voiture)
                                                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(67, 67, 67)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nb_porte, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(annee)
                                                    .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(type_energie, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(model)
                                        .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(couleur)
                                            .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                                .addComponent(nb_place, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(406, 406, 406)))
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(545, 545, 545))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(559, 559, 559)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb_porte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(c_voiture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(marque, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(n_voiture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(killo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(105, 105, 105)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nb_place, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(89, 89, 89)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(type_boite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(type_energie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(type_voiture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        voiture vt=new voiture(this);
        vt.setVisible(true);
        model.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void marqueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marqueFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueFocusGained

    private void marqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marqueActionPerformed
public void test1(String fam) {
        model.setText(fam);
        
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String fam=marque.getText();
        if (fam.equals("")){
            JOptionPane.showMessageDialog(null, "il faux rempilir champs famille !!!");
        }
        else{
          marque sf=new marque(this,fam);
          sf.setVisible(true);
          
        }
        

    }//GEN-LAST:event_jButton4ActionPerformed
public void test(String fam) {
       marque.setText(fam);
        
    }
    private void modelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelFocusGained

    }//GEN-LAST:event_modelFocusGained

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void c_voitureFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_voitureFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_c_voitureFocusGained

    private void c_voitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_voitureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_voitureActionPerformed

    private void n_voitureFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n_voitureFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_n_voitureFocusGained

    private void n_voitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_voitureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_voitureActionPerformed

    private void killoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_killoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_killoFocusGained

    private void killoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_killoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_killoActionPerformed

    private void anneeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anneeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_anneeFocusGained

    private void anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anneeActionPerformed

    private void couleurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_couleurFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_couleurFocusGained

    private void couleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couleurActionPerformed
      
    }//GEN-LAST:event_couleurActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        couleur cl=new couleur(this);
        cl.setVisible(true);
        //couleur.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nb_placeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nb_placeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nb_placeFocusGained

    private void nb_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nb_placeActionPerformed

    private void nb_porteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nb_porteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nb_porteFocusGained

    private void nb_porteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb_porteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nb_porteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        menu mn=new menu();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!marque.getText().equals("") && !model.getText().equals("")&& !killo.getText().equals("") && !couleur.getText().equals("") && !annee.getText().equals("") && !n_voiture.getText().equals("")&& !nb_place.getText().equals("") && !nb_porte.getText().equals("") && !type_voiture.getSelectedItem().equals("SELECTIONNEZ TYPE DE VOITURE") && !type_boite.getSelectedItem().equals("SELECTIONNEZ TYPE DE BOITE") && !type_energie.getSelectedItem().equals("SELECTIONNEZ TYPE D'ENERGIE ")){
            try{
                  Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/car_rent",
                    "root", "Asusthgu.1");
                Statement stmt = con.createStatement();
                ResultSet rs= stmt.executeQuery("select code_voiture from voiture order by code_voiture desc");
                rs.next();
                int a =rs.getInt(1);
                int aa=a+1;
                //JOptionPane.showMessageDialog(null, aa);
                String aaa=Integer.toString(aa);
                //JOptionPane.showMessageDialog(null, aa);
                if(aa<10){
                    c_voiture.setText("00000"+aaa);
                }
                if(aa>9 && aa<100){
                    c_voiture.setText("0000"+aaa);
                }
                if(aa>99 && aa<1000){
                    c_voiture.setText("000"+aaa);
                }
                if(aa>999 && aa<10000){
                    c_voiture.setText("00"+aaa);
                }
                if(aa>9999 && aa<100000){
                    c_voiture.setText("0"+aaa);
                }
                if(aa>99999 && aa<1000000){
                    c_voiture.setText( aaa);
                }
                try{
                    Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                Connection conx = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/car_rent",
                    "root", "Asusthgu.1");
                PreparedStatement ps = conx.prepareStatement("insert into voiture (model,marque,code_voiture,num_voiture,killmetrage,annee,couleur,nb_place,nb_prote,t_voiture,t_boite,t_energie)"
                    +" values (?,?,?,?,?,?,?,?,?,?,?,?)");
                 String c_v=c_voiture.getText();
                ps.setString(1, ""+model.getText()+"");
                ps.setString(2, ""+marque.getText()+"");
                ps.setString(3, ""+c_v+"");
                ps.setString(4, ""+n_voiture.getText()+"");
                killo.setText(killo.getText()+" KM");
                String kill=killo.getText();
                ps.setString(5, ""+kill+" ");
                int ann=Integer.parseInt(annee.getText());
                ps.setInt(6, ann);
                ps.setString(7, ""+couleur.getText()+"");
                int n_p=Integer.parseInt(nb_place.getText());
                ps.setInt(8, n_p);
                int n_po=Integer.parseInt(nb_porte.getText());
                ps.setInt(9, n_po);
                ps.setString(10, ""+type_voiture.getSelectedItem()+"");
                ps.setString(11, ""+type_boite.getSelectedItem()+"");
                ps.setString(12, ""+type_energie.getSelectedItem()+"");
                int rowsInserted = ps.executeUpdate();
                if (rowsInserted > 0) {
                    UIManager.put("Panel.background", Color.GREEN);
                JOptionPane.showMessageDialog(null,c_voiture.getText(), "le code de voiture est ",JOptionPane.PLAIN_MESSAGE);
                //JOptionPane.showInternalConfirmDialog(null,"test");
                 
                JOptionPane.showMessageDialog(null, "voiture ajouter avec succes !! ","INFO",JOptionPane.INFORMATION_MESSAGE);
                
                
                }
                else {
                    JOptionPane.showMessageDialog(null, "il y a une erruer!! ");
                }
                }
                
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "il faux remplir les champs");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void test2(String fam) {
        
        couleur.setText(fam);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajout_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajout_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajout_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajout_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajout_voiture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annee;
    private javax.swing.JTextField c_voiture;
    private javax.swing.JTextField couleur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField killo;
    private javax.swing.JTextField marque;
    private javax.swing.JTextField model;
    private javax.swing.JTextField n_voiture;
    private javax.swing.JTextField nb_place;
    private javax.swing.JTextField nb_porte;
    private javax.swing.JComboBox<String> type_boite;
    private javax.swing.JComboBox<String> type_energie;
    private javax.swing.JComboBox<String> type_voiture;
    // End of variables declaration//GEN-END:variables

 
}
