/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rent;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEvent;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Scanner;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author abdelrahman
 */
public class location extends javax.swing.JFrame {

    /**
     * Creates new form location
     */
    public location() {
        initComponents();
        Dimension dim=getToolkit().getScreenSize();
        this.setSize(dim);
       marque.setBackground(new java.awt.Color(0,0,0,1));
       model.setBackground(new java.awt.Color(0,0,0,1));
       c_voiture.setBackground(new java.awt.Color(0,0,0,1));
       nom.setBackground(new java.awt.Color(0,0,0,1));
       prenom.setBackground(new java.awt.Color(0,0,0,1));
       code.setBackground(new java.awt.Color(0,0,0,1));
       pj.setBackground(new java.awt.Color(0,0,0,1));
       pt.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validate = new javax.swing.JCheckBox();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        marque = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        model = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        c_voiture = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        dd = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        df = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        pj = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        pt = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        validate.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dungeon", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Car_Rental_40px.png"))); // NOI18N
        jLabel1.setText("   CAR-LOCO");

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("LOCATION DE VOITURE ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_user_40px_1.png"))); // NOI18N

        user_name.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        user_name.setForeground(new java.awt.Color(0, 0, 0));
        user_name.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                user_nameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        date1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        date1.setForeground(new java.awt.Color(0, 0, 0));
        date1.setText("a");
        date1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                date1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_calendar_40px.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_clock_40px.png"))); // NOI18N

        date.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 0, 0));
        date.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_car_50px.png"))); // NOI18N
        jButton3.setText("MARQUE");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        marque.setBackground(new java.awt.Color(255, 255, 255));
        marque.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        marque.setForeground(new java.awt.Color(0, 0, 0));
        marque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marque.setBorder(null);

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator22.setForeground(new java.awt.Color(0, 0, 0));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_steering_wheel_50px.png"))); // NOI18N
        jButton4.setText("MODELE");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        model.setBackground(new java.awt.Color(255, 255, 255));
        model.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        model.setForeground(new java.awt.Color(0, 0, 0));
        model.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        model.setBorder(null);

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CODE VOITURE");

        c_voiture.setBackground(new java.awt.Color(255, 255, 255));
        c_voiture.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        c_voiture.setForeground(new java.awt.Color(0, 0, 0));
        c_voiture.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_voiture.setBorder(null);

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_redeem_30px.png"))); // NOI18N
        jLabel7.setText("code");

        code.setBackground(new java.awt.Color(255, 255, 255));
        code.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        code.setForeground(new java.awt.Color(0, 0, 0));
        code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        code.setBorder(null);
        code.setCaretColor(new java.awt.Color(255, 255, 255));

        nom.setBackground(new java.awt.Color(255, 255, 255));
        nom.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 0, 0));
        nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_name_30px_1.png"))); // NOI18N
        jLabel8.setText("nom");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_resume_30px.png"))); // NOI18N
        jLabel9.setText("prenom");

        prenom.setBackground(new java.awt.Color(255, 255, 255));
        prenom.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(0, 0, 0));
        prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prenom.setBorder(null);

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_search_20px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dd.setDateFormatString("dd-MM-yyyy");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_time_30px.png"))); // NOI18N
        jLabel10.setText("DEBUT");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_time_30px.png"))); // NOI18N
        jLabel11.setText("FIN");

        df.setDateFormatString("dd-MM-yyyy");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Dollar_Coin_30px_1.png"))); // NOI18N
        jLabel12.setText("PRIX/J");

        pj.setBackground(new java.awt.Color(255, 255, 255));
        pj.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        pj.setForeground(new java.awt.Color(0, 0, 0));
        pj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pj.setBorder(null);

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Dollar_Coin_30px_1.png"))); // NOI18N
        jLabel13.setText("PRIX TOTAL");

        pt.setBackground(new java.awt.Color(255, 255, 255));
        pt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        pt.setForeground(new java.awt.Color(0, 0, 0));
        pt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pt.setBorder(null);
        pt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ptMousePressed(evt);
            }
        });

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_save_50px.png"))); // NOI18N
        jButton2.setText("ENREGISTER");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_print_50px.png"))); // NOI18N
        jButton5.setText("IMPRIMER");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Login_50px.png"))); // NOI18N
        jButton6.setText("RETOUR");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_search_20px.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(358, 358, 358)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(43, 43, 43)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator11)
                                    .addComponent(pt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(df, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(user_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(marque)
                                                    .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48))
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46))))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(298, 298, 298)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_voiture, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(497, 497, 497))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(marque, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16))
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton7)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(c_voiture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4))
                                .addGap(62, 62, 62)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(df, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(pj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(60, 60, 60)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_nameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_user_nameAncestorAdded
        try {
            FileReader fr = new FileReader("C:\\Users\\abdelrahman\\OneDrive\\Bureau\\cours\\projet\\car-loco\\src\\car_rent\\nom_util.txt");
            Scanner myReader = new Scanner(fr);
            String data = myReader.nextLine();
            user_name.setText(data.toUpperCase());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_user_nameAncestorAdded

    private void date1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_date1AncestorAdded
        Date d=new Date();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy ");
        String s=dtf.format(LocalDateTime.now());
        date1.setText(s);
    }//GEN-LAST:event_date1AncestorAdded

    private void dateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateAncestorAdded
        Thread clock = new Thread() {
            @Override
            public void run() {
                while (true) { //boucle éternelle
                    Calendar cal = new GregorianCalendar();
                    int h = cal.get(Calendar.HOUR_OF_DAY);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    date.setText(String.valueOf(h)+" h "+String.valueOf(min)+" min "+String.valueOf(sec)+" s ");
                    try {
                        sleep(500); // dormir une demi seconde
                    } catch (InterruptedException ie) {
                    } // l'exception n'est pas traitée dans notre cas
                }
            }
        };
        clock.start();
    }//GEN-LAST:event_dateAncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        voiture vt=new voiture(this);
        vt.setVisible(true);
        model.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String fam=marque.getText();
        if (fam.equals("")){
            JOptionPane.showMessageDialog(null, "il faux rempilir champs famille !!!");
        }
        else{
            marque sf=new marque(this,fam);
            sf.setVisible(true);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        client cl=new client(this);
        cl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
   
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        
        
         String code_client="";
     String nom_client="";
     String pre_client="";
     String c_pays="";
     String matricule="";
     String nom_pays="";
     String adrr="";
     String ville_client="";
     String telphone="";
     String fax1="";
     String code_voiture="";
     String model_voiture="";
     String marque_voiture="";
     String n_voiture="";
     String k_voiture="";
     String ann_voiture="";
     String coul_voiture="";
     String place_voitrue="";
     String prote_voiture="";
     String type_voiture="";
     String boite_voiture="";
     String energie_voiture="";
        if(!marque.getText().equals("") && !model.getText().equals("")&& !code.getText().equals("") && !c_voiture.getText().equals("") && !nom.getText().equals("") && !prenom.getText().equals("")&& !pj.getText().equals("") && !pt.getText().equals("") && !dd.getDate().equals(null) && !df.getDate().equals(null)){
            try{
                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/car_rent",
                    "root", "Asusthgu.1");
                Statement stmt = con.createStatement();
                ResultSet rs= stmt.executeQuery("select nom_cl,pre_cl,mf,code_pays,lib_pays,adress,ville,tel,fax,code_cl from client where code_cl='"+code.getText()+"' ");
                if(rs.next()){
                        
                         nom_client=rs.getString(1);
                         pre_client=rs.getString(2);
                        matricule=rs.getString(3);
                        c_pays=rs.getString(4);
                        nom_pays=rs.getString(5);
                       adrr=rs.getString(6);
                       ville_client=rs.getString(7);
                       telphone=rs.getString(8);
                        fax1=rs.getString(9);
                        code_client=rs.getString(10);
                }
              
            
               try{
                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                Connection con1 = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/car_rent",
                    "root", "Asusthgu.1");
                Statement stmt1 = con1.createStatement();
                ResultSet rs1= stmt1.executeQuery("select * from voiture where code_voiture='"+c_voiture.getText()+"' ");
                if(rs1.next()){
                        
                         model_voiture=rs1.getString(2);
                         marque_voiture=rs1.getString(3);
                        code_voiture=rs1.getString(4);
                        n_voiture=rs1.getString(5);
                        k_voiture=rs1.getString(6);
                       ann_voiture=rs1.getString(7);
                       coul_voiture=rs1.getString(8);
                       place_voitrue=rs1.getString(9);
                        prote_voiture=rs1.getString(10);
                        type_voiture=rs1.getString(11);
                        boite_voiture=rs1.getString(12);
                        energie_voiture=rs1.getString(13);
                }
                else{
                    JOptionPane.showMessageDialog(null, "voiture n'existe pas ");
                }
               try{
                    Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                    Connection conx = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/car_rent",
                        "root", "Asusthgu.1");
                    PreparedStatement ps = conx.prepareStatement("insert into location (nom_cl,pre_cl,mf,code_pays,lib_pays,adress,ville,tel,fax,code_cl,model,marque,code_voiture,num_voiture,killmetrage,annee,couleur,nb_place,nb_prote,t_voiture,t_boite,t_energie,date_d,date_f,prix_j,prix_tot)"
                        +" values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                   ps.setString(1,""+nom_client+"");
                   ps.setString(2,""+pre_client+"");
                   ps.setString(3,""+matricule+"");
                   ps.setString(4,""+c_pays+"");
                   ps.setString(5,""+nom_pays+"");
                   ps.setString(6,""+adrr+"");
                   ps.setString(7,""+ville_client+"");
                   int tel_cl =Integer.parseInt(telphone);
                   int fax_cl=Integer.parseInt(fax1);
                   ps.setInt(8,tel_cl);
                   ps.setInt(9,fax_cl);
                   ps.setString(10,""+code_client+"");
                   ps.setString(11,""+model_voiture+"");
                   ps.setString(12,""+marque_voiture+"");
                   ps.setString(13,""+code_voiture+"");
                   ps.setString(14,""+n_voiture+"");
                   ps.setString(15,""+k_voiture+"");
                   int annn=Integer.parseInt(ann_voiture);
                   ps.setInt(16,annn);
                   ps.setString(17,""+coul_voiture+"");
                   int nbplaces=Integer.parseInt(place_voitrue);
                   ps.setInt(18,nbplaces);
                   int nbporte=Integer.parseInt(prote_voiture);
                   ps.setInt(19,nbporte);
                   ps.setString(20,""+type_voiture+"");
                   ps.setString(21,""+boite_voiture+"");
                   ps.setString(22,""+energie_voiture+"");
                   Date datedeb = dd.getDate();

            SimpleDateFormat dateFormatdd = new SimpleDateFormat("dd-MM-yyyy");
            String formattedDatedd = dateFormatdd.format(datedeb);
                   ps.setString(23,""+formattedDatedd+"");
                   Date datefin = df.getDate();

            SimpleDateFormat dateFormatdf = new SimpleDateFormat("dd-MM-yyyy");
            String formattedDatedf = dateFormatdf.format(datefin);
                   ps.setString(24,""+formattedDatedf+"");
                   ps.setString(25,""+pj.getText()+"");
                   ps.setString(26,""+pt.getText()+"");
                   
                    int rowsInserted = ps.executeUpdate();
                    if (rowsInserted > 0) {
                       

                        JOptionPane.showMessageDialog(null, "voiture louer avec succes !! ","INFO",JOptionPane.INFORMATION_MESSAGE);
                   
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "il y a une erruer!! ");
                    }
                }

                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
               
               
               
               
               }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
            
            
            validate.setSelected(true);
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
              
            
        }
        else{
            JOptionPane.showMessageDialog(null, "il faux remplir les champs");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(validate.isSelected()){
        
        
        com.itextpdf.text.Rectangle pageSize = PageSize.A4;
        float marginLeft = 36;
        float marginRight = 36;
        float marginTop = 36;
        float marginBottom = 36;

        // Create a new PDF document
        Document document = new Document(pageSize, marginLeft, marginRight, marginTop, marginBottom);

        try {
            // Create a new PDF writer
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("facture\\invoice_"+nom.getText()+".pdf"));

            // Define a header and footer
          

            // Open the document
            document.open();

            // Add the logo to the header
            Image logo = Image.getInstance("logo_car_loco1.png");
            logo.scaleToFit(100, 100);
            logo.setAbsolutePosition(marginLeft, pageSize.getHeight() - marginTop - logo.getScaledHeight());
            document.add(logo);
            
            
            
            Image sing = Image.getInstance("C:\\Users\\abdelrahman\\OneDrive\\Bureau\\cours\\projet\\car-loco\\src\\car_rent\\signa1.png");
            sing.scaleToFit(300, 300);
            
            sing.setAbsolutePosition((pageSize.getWidth() - logo.getScaledWidth()) / 2, 20);
            document.add(sing);

            // Add the customer information to the header
            Paragraph customerInfo = new Paragraph();
            customerInfo.add(new Chunk("Customer Information  \n\n\n\n",new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD, BaseColor.BLUE)));
            customerInfo.add(new Chunk("\n"));
            customerInfo.add(new Chunk("CODE CLIENT : "+code.getText()+"\n\n" ,new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD, BaseColor.BLUE)));
            customerInfo.add(new Chunk("NOM : "+nom.getText()+"\n\n\n",new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD, BaseColor.BLUE)));
            customerInfo.add(new Chunk("PRENOM : "+prenom.getText()+"\n\n\n\n\n\n ",new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD, BaseColor.BLUE)));
            
            customerInfo.setAlignment(Element.ALIGN_RIGHT);
            document.add(customerInfo);

            // Add the rental details to a table in the center of the page
            PdfPTable rentalTable = new PdfPTable(6);
            rentalTable.setWidthPercentage(100);
            rentalTable.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            rentalTable.getDefaultCell().setVerticalAlignment(Element.ALIGN_MIDDLE);
            rentalTable.addCell(new PdfPCell(new Phrase("Car Name")));
            rentalTable.addCell(new PdfPCell(new Phrase("Car Model")));
            rentalTable.addCell(new PdfPCell(new Phrase("Start Date")));
            rentalTable.addCell(new PdfPCell(new Phrase("End Date")));
            rentalTable.addCell(new PdfPCell(new Phrase("Price per Day")));
            rentalTable.addCell(new PdfPCell(new Phrase("Total Price")));
            rentalTable.setHeaderRows(1);
            rentalTable.addCell(marque.getText());
            rentalTable.addCell(model.getText());
            Date datedeb = dd.getDate();

            SimpleDateFormat dateFormatdd = new SimpleDateFormat("dd-MM-yyyy");
            String formattedDatedd = dateFormatdd.format(datedeb);
            rentalTable.addCell(formattedDatedd);
            
            
              Date datefin = df.getDate();

            SimpleDateFormat dateFormatdf = new SimpleDateFormat("dd-MM-yyyy");
            String formattedDatedf = dateFormatdf.format(datefin);
            rentalTable.addCell(formattedDatedf);
            rentalTable.addCell(pj.getText()+" DT");
            rentalTable.addCell(pt.getText()+" DT");
            
            document.add(rentalTable);
           

            // Add a signature rectangle to the footer
            PdfContentByte cb = writer.getDirectContent();
            cb.stroke();

            // Close the document
            document.close();
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        File file = new File("C:\\Users\\abdelrahman\\OneDrive\\Bureau\\cours\\projet\\car-loco\\facture\\invoice_"+nom.getText()+".pdf");  
        Desktop desktop = Desktop.getDesktop();
         try {  
            desktop.open(file);
        } catch (IOException ex) {
            Logger.getLogger(location.class.getName()).log(Level.SEVERE, null, ex);
        }}else{
    JOptionPane.showMessageDialog(null,"il faut enregistrer dabord");
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         menu mn=new menu();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptMousePressed
       Date startDate = dd.getDate();
                        Date endDate = df.getDate();
                        long timeDiff = (endDate.getTime() - startDate.getTime());
                        


                        long daysDiff = (timeDiff / (1000 * 60 * 60 * 24))+1;
                        int prix_jour=Integer.parseInt(pj.getText());
                        long prix_total=daysDiff * prix_jour;
                        String pitot = Long.toString(prix_total);
                        pt.setText(pitot);
    }//GEN-LAST:event_ptMousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String fam=marque.getText();
        String fam1=model.getText();
        
        if (fam.equals("") && fam1.equals("") ){
            JOptionPane.showMessageDialog(null, "il faux rempilir champs famille !!!");
        }
        else{
            code_vt sf=new code_vt(this,fam,fam1);
            sf.setVisible(true);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new location().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_voiture;
    private javax.swing.JTextField code;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private com.toedter.calendar.JDateChooser dd;
    private com.toedter.calendar.JDateChooser df;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField marque;
    private javax.swing.JTextField model;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pj;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField pt;
    private javax.swing.JLabel user_name;
    private javax.swing.JCheckBox validate;
    // End of variables declaration//GEN-END:variables

    void locate(String nom_cl, String pre_cl, String code_cl) {
            code.setText(code_cl);
            nom.setText(nom_cl);
            prenom.setText(pre_cl);
    }

    void vt(String type) {
        marque.setText(type);
    }

    void mod(String value) {
        model.setText(value);
    }

    void tesa(String valuer) {
        c_voiture.setText(valuer);
    }

 
}
