/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rent;
import java.awt.Color;
import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Scanner;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author abdelrahman
 */
public class mise_a_jour_client extends javax.swing.JFrame {

    /**
     * Creates new form mise_a_jour_client
     */
    public mise_a_jour_client() {
        initComponents();
            Dimension dim=getToolkit().getScreenSize();
        this.setSize(dim);
       nom.setBackground(new java.awt.Color(0,0,0,1));
       prenom.setBackground(new java.awt.Color(0,0,0,1));
       tel.setBackground(new java.awt.Color(0,0,0,1));
       fax.setBackground(new java.awt.Color(0,0,0,1));
       id_pays.setBackground(new java.awt.Color(0,0,0,1));
       lib_pays.setBackground(new java.awt.Color(0,0,0,1));
       m_f.setBackground(new java.awt.Color(0,0,0,1));
       ville.setBackground(new java.awt.Color(0,0,0,1));
       code.setBackground(new java.awt.Color(0,0,0,1));
       adr.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jSeparator2 = new javax.swing.JSeparator();
        code = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        m_f = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        id_pays = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        adr = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        ville = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        lib_pays = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 255));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        code.setBackground(new java.awt.Color(255, 255, 255));
        code.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        code.setForeground(new java.awt.Color(0, 0, 0));
        code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        code.setBorder(null);
        code.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_redeem_30px.png"))); // NOI18N
        jLabel1.setText("code");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_name_30px_1.png"))); // NOI18N
        jLabel2.setText("nom");

        nom.setBackground(new java.awt.Color(255, 255, 255));
        nom.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 0, 0));
        nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_department_30px.png"))); // NOI18N
        jLabel3.setText("matricule fiscale");

        m_f.setBackground(new java.awt.Color(255, 255, 255));
        m_f.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        m_f.setForeground(new java.awt.Color(0, 0, 0));
        m_f.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_f.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_america_30px.png"))); // NOI18N
        jLabel4.setText("code pays");

        id_pays.setBackground(new java.awt.Color(255, 255, 255));
        id_pays.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        id_pays.setForeground(new java.awt.Color(0, 0, 0));
        id_pays.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_pays.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_region_30px.png"))); // NOI18N
        jLabel5.setText("adress");

        adr.setBackground(new java.awt.Color(255, 255, 255));
        adr.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        adr.setForeground(new java.awt.Color(0, 0, 0));
        adr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        adr.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_exterior_30px.png"))); // NOI18N
        jLabel6.setText("ville");

        ville.setBackground(new java.awt.Color(255, 255, 255));
        ville.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ville.setForeground(new java.awt.Color(0, 0, 0));
        ville.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ville.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_phone_30px.png"))); // NOI18N
        jLabel7.setText("telephone");

        tel.setBackground(new java.awt.Color(255, 255, 255));
        tel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 0, 0));
        tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tel.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_resume_30px.png"))); // NOI18N
        jLabel8.setText("prenom");

        prenom.setBackground(new java.awt.Color(255, 255, 255));
        prenom.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(0, 0, 0));
        prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prenom.setBorder(null);

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        lib_pays.setBackground(new java.awt.Color(255, 255, 255));
        lib_pays.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lib_pays.setForeground(new java.awt.Color(0, 0, 0));
        lib_pays.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lib_pays.setBorder(null);

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_fax_30px.png"))); // NOI18N
        jLabel9.setText("fax");

        fax.setBackground(new java.awt.Color(255, 255, 255));
        fax.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        fax.setForeground(new java.awt.Color(0, 0, 0));
        fax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fax.setBorder(null);

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MISE A JOUR CLIENT");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_user_40px_1.png"))); // NOI18N

        user_name.setForeground(new java.awt.Color(0, 0, 0));
        user_name.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                user_nameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        date1.setForeground(new java.awt.Color(0, 0, 0));
        date1.setText("a");
        date1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                date1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_calendar_40px.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_clock_40px.png"))); // NOI18N

        date.setForeground(new java.awt.Color(0, 0, 0));
        date.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel14.setFont(new java.awt.Font("Dungeon", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Car_Rental_40px.png"))); // NOI18N
        jLabel14.setText("   CAR-LOCO");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_search_20px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_submit_for_approval_50px.png"))); // NOI18N
        jButton6.setText("GENERER");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_upgrade_50px_2.png"))); // NOI18N
        jButton2.setText("MISE A JOUR");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_Login_50px.png"))); // NOI18N
        jButton5.setText("RETOUR");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_search_20px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(345, 345, 345)
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(user_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(136, 136, 136)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(319, 319, 319))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(id_pays)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(code)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nom)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(m_f)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ville)
                                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(adr)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fax)
                                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(prenom)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lib_pays)
                                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(418, 418, 418))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(458, 458, 458))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(59, 59, 59)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(m_f, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lib_pays, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(id_pays, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3))))
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_nameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_user_nameAncestorAdded
        try {
            FileReader fr = new FileReader("E:\\MY LIFE\\COURS\\INFORMATIQUE\\JAVA\\JavaApplication1\\src\\myapps\\nom_util.txt");
            Scanner myReader = new Scanner(fr);
            String data = myReader.nextLine();
            user_name.setText(data.toUpperCase());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_user_nameAncestorAdded

    private void date1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_date1AncestorAdded
        Date d=new Date();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy ");
        String s=dtf.format(LocalDateTime.now());
        date1.setText(s);
    }//GEN-LAST:event_date1AncestorAdded

    private void dateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateAncestorAdded
        Thread clock = new Thread() {
            @Override
            public void run() {
                while (true) { //boucle éternelle
                    Calendar cal = new GregorianCalendar();
                    int h = cal.get(Calendar.HOUR_OF_DAY);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    date.setText(String.valueOf(h)+" h "+String.valueOf(min)+" min "+String.valueOf(sec)+" s ");
                    try {
                        sleep(500); // dormir une demi seconde
                    } catch (InterruptedException ie) {
                    } // l'exception n'est pas traitée dans notre cas
                }
            }
        };
        clock.start();
    }//GEN-LAST:event_dateAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       client cl=new client(this);
       cl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try{
            Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/car_rent",
                "root", "Asusthgu.1");
            Statement stmt = con.createStatement();
            ResultSet rs= stmt.executeQuery("select nom_cl,pre_cl,mf,code_pays,lib_pays,adress,ville,tel,fax from client where code_cl='"+code.getText()+"' ");
            while(rs.next()){
                nom.setText(rs.getString(1));
                prenom.setText(rs.getString(2));
                m_f.setText(rs.getString(3));
                id_pays.setText(rs.getString(4));
                lib_pays.setText(rs.getString(5));
                adr.setText(rs.getString(6));
                ville.setText(rs.getString(7));
                tel.setText(rs.getString(8));
                fax.setText(rs.getString(9));
               

            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int a=0;
        if(!nom.getText().equals("") && !prenom.getText().equals("")&& !m_f.getText().equals("") && !id_pays.getText().equals("") && !lib_pays.getText().equals("") && !adr.getText().equals("")&& !ville.getText().equals("") && !tel.getText().equals("") && !fax.getText().equals("")){

            try{
                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/car_rent",
                    "root", "Asusthgu.1");
                Statement stmt = con.createStatement();
                ResultSet rs= stmt.executeQuery("select nom_cl,pre_cl,mf,code_pays,lib_pays,adress,ville,tel,fax from client where code_cl='"+code.getText()+"'");
                while(rs.next()){
                    if (a==0){
                        if (!nom.getText().equals(rs.getString(1))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET nom_cl='"+nom.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "nom du client est mise a joure");

                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
                        }
                        if (!prenom.getText().equals(rs.getString(2))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET pre_cl='"+prenom.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "prenom du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
                        }
                        if (!m_f.getText().equals(rs.getString(3)) ){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET mf='"+m_f.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "matricule fiscale du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
                        }
                        if (!id_pays.getText().equals(rs.getString(4))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET code_pays='"+id_pays.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "code pays du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }

                        }
                        if (!lib_pays.getText().equals(rs.getString(5))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET lib_pays='"+lib_pays.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "pays du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }

                        }
                        if (!adr.getText().equals(rs.getString(6))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET adress='"+adr.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "adress du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }

                        }
                        if (!ville.getText().equals(rs.getString(7))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET ville='"+ville.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "adress du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }

                        }

                        if (!tel.getText().equals(rs.getString(8))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET tel='"+tel.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "numero de telephone du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }

                        }
                        if (!fax.getText().equals(rs.getString(9))){
                            try{
                                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                                Connection conx = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/car_rent",
                                    "root", "Asusthgu.1");
                                Statement stmt1 = conx.createStatement();
                                String sql = "UPDATE client SET fax='"+fax.getText()+"' where code_cl='"+code.getText()+"'";
                                stmt1.executeUpdate(sql);
                                a=1;
                                JOptionPane.showMessageDialog(null, "numero de fax du client est mise a joure");
                            }
                            catch(Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }

                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "aucun chapms a ete mise a joure");
                    }

                }
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }}

            /*try{
                Class.forName ("com.mysql.cj.jdbc.Driver").newInstance();
                Connection conx = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/car_rent",
                    "root", "Asusthgu.1");
                PreparedStatement ps = conx.prepareStatement("insert into voiture (model,marque,code_voiture,num_voiture,killmetrage,annee,couleur,nb_place,nb_prote,t_voiture,t_boite,t_energie)"
                    +" values (?,?,?,?,?,?,?,?,?,?,?,?)");
                String c_v=c_voiture.getText();
                ps.setString(1, ""+model.getText()+"");
                ps.setString(2, ""+marque.getText()+"");
                ps.setString(3, ""+c_v+"");
                ps.setString(4, ""+n_voiture.getText()+"");
                killo.setText(killo.getText()+" KM");
                String kill=killo.getText();
                ps.setString(5, ""+kill+" ");
                int ann=Integer.parseInt(annee.getText());
                ps.setInt(6, ann);
                ps.setString(7, ""+couleur.getText()+"");
                int n_p=Integer.parseInt(nb_place.getText());
                ps.setInt(8, n_p);
                int n_po=Integer.parseInt(nb_porte.getText());
                ps.setInt(9, n_po);
                ps.setString(10, ""+type_voiture.getSelectedItem()+"");
                ps.setString(11, ""+type_boite.getSelectedItem()+"");
                ps.setString(12, ""+type_energie.getSelectedItem()+"");
                int rowsInserted = ps.executeUpdate();
                if (rowsInserted > 0) {
                    UIManager.put("Panel.background", Color.GREEN);
                    JOptionPane.showMessageDialog(null,c_voiture.getText(), "le code de voiture est ",JOptionPane.PLAIN_MESSAGE);
                    //JOptionPane.showInternalConfirmDialog(null,"test");

                    JOptionPane.showMessageDialog(null, "voiture ajouter avec succes !! ","INFO",JOptionPane.INFORMATION_MESSAGE);

                }
                else {
                    JOptionPane.showMessageDialog(null, "il y a une erruer!! ");
                }
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "il faux remplir les champs");
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        menu mn=new menu();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pays cl=new pays(this);
        cl.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mise_a_jour_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mise_a_jour_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mise_a_jour_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mise_a_jour_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mise_a_jour_client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adr;
    private javax.swing.JTextField code;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField fax;
    private javax.swing.JTextField id_pays;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField lib_pays;
    private javax.swing.JTextField m_f;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField tel;
    private javax.swing.JLabel user_name;
    private javax.swing.JTextField ville;
    // End of variables declaration//GEN-END:variables

    void test21(String value) {
        code.setText(value);
    }

    void test21(String value, String value1) {
         id_pays.setText(value1);
     lib_pays.setText(value);
    }
}
