/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car_rent;

/**
 *
 * @author abdelrahman
 */
public class voiture extends javax.swing.JFrame {
    public ajout_voiture frame;
    public mise_a_jour_voiture frame1;
    public location frame2;
    /**
     * Creates new form voiture
     */
    public voiture() {
        initComponents();
    }
    public voiture(ajout_voiture f) {
        frame = f;
        
        initComponents();
        dispose();
    }
    public voiture(mise_a_jour_voiture f1) {
        frame1 = f1;
        initComponents();
        dispose();
    }
     public voiture(location f2) {
        frame2 = f2;
        initComponents();
        dispose();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        audi = new javax.swing.JButton();
        bmw = new javax.swing.JButton();
        chevr = new javax.swing.JButton();
        fiat = new javax.swing.JButton();
        ford = new javax.swing.JButton();
        hyn = new javax.swing.JButton();
        kia = new javax.swing.JButton();
        mazda = new javax.swing.JButton();
        mits = new javax.swing.JButton();
        merc = new javax.swing.JButton();
        nissan = new javax.swing.JButton();
        ren = new javax.swing.JButton();
        suz = new javax.swing.JButton();
        toy = new javax.swing.JButton();
        volk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        audi.setBackground(new java.awt.Color(255, 255, 255));
        audi.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        audi.setForeground(new java.awt.Color(0, 0, 0));
        audi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_audi_30px.png"))); // NOI18N
        audi.setText("AUDI");
        audi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        audi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        audi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        audi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                audiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                audiMouseReleased(evt);
            }
        });
        audi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiActionPerformed(evt);
            }
        });

        bmw.setBackground(new java.awt.Color(255, 255, 255));
        bmw.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bmw.setForeground(new java.awt.Color(0, 0, 0));
        bmw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_bmw_30px_1.png"))); // NOI18N
        bmw.setText("BMW");
        bmw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bmw.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bmw.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bmw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmwMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bmwMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bmwMouseReleased(evt);
            }
        });
        bmw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmwActionPerformed(evt);
            }
        });

        chevr.setBackground(new java.awt.Color(255, 255, 255));
        chevr.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chevr.setForeground(new java.awt.Color(0, 0, 0));
        chevr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_chevrolet_30px.png"))); // NOI18N
        chevr.setText("CHEVROLET");
        chevr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chevr.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        chevr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chevr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chevrMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chevrMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chevrMouseReleased(evt);
            }
        });
        chevr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chevrActionPerformed(evt);
            }
        });

        fiat.setBackground(new java.awt.Color(255, 255, 255));
        fiat.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        fiat.setForeground(new java.awt.Color(0, 0, 0));
        fiat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_fiat_30px.png"))); // NOI18N
        fiat.setText("FIAT");
        fiat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fiat.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fiat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fiat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fiatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fiatMouseReleased(evt);
            }
        });
        fiat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiatActionPerformed(evt);
            }
        });

        ford.setBackground(new java.awt.Color(255, 255, 255));
        ford.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ford.setForeground(new java.awt.Color(0, 0, 0));
        ford.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_ford_30px.png"))); // NOI18N
        ford.setText("FORD");
        ford.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ford.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ford.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ford.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fordMouseReleased(evt);
            }
        });
        ford.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fordActionPerformed(evt);
            }
        });

        hyn.setBackground(new java.awt.Color(255, 255, 255));
        hyn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        hyn.setForeground(new java.awt.Color(0, 0, 0));
        hyn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_hyundai_30px.png"))); // NOI18N
        hyn.setText("HYUNDAI");
        hyn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hyn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        hyn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        hyn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hynMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hynMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hynMouseReleased(evt);
            }
        });
        hyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hynActionPerformed(evt);
            }
        });

        kia.setBackground(new java.awt.Color(255, 255, 255));
        kia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        kia.setForeground(new java.awt.Color(0, 0, 0));
        kia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_kia_30px.png"))); // NOI18N
        kia.setText("KIA");
        kia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kiaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kiaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                kiaMouseReleased(evt);
            }
        });
        kia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiaActionPerformed(evt);
            }
        });

        mazda.setBackground(new java.awt.Color(255, 255, 255));
        mazda.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        mazda.setForeground(new java.awt.Color(0, 0, 0));
        mazda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_mazda_30px.png"))); // NOI18N
        mazda.setText("MAZDA");
        mazda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mazda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mazda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mazda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mazdaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mazdaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mazdaMouseReleased(evt);
            }
        });
        mazda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mazdaActionPerformed(evt);
            }
        });

        mits.setBackground(new java.awt.Color(255, 255, 255));
        mits.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        mits.setForeground(new java.awt.Color(0, 0, 0));
        mits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_mitsubishi_30px.png"))); // NOI18N
        mits.setText("MITSUBISHI");
        mits.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mits.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mits.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mitsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mitsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mitsMouseReleased(evt);
            }
        });
        mits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitsActionPerformed(evt);
            }
        });

        merc.setBackground(new java.awt.Color(255, 255, 255));
        merc.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        merc.setForeground(new java.awt.Color(0, 0, 0));
        merc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_mercedes_benz_30px.png"))); // NOI18N
        merc.setText("MERCEDES");
        merc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        merc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        merc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        merc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mercMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mercMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mercMouseReleased(evt);
            }
        });
        merc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercActionPerformed(evt);
            }
        });

        nissan.setBackground(new java.awt.Color(255, 255, 255));
        nissan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        nissan.setForeground(new java.awt.Color(0, 0, 0));
        nissan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_nissan_30px.png"))); // NOI18N
        nissan.setText("NISSAN");
        nissan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nissan.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nissan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nissan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nissanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nissanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nissanMouseReleased(evt);
            }
        });
        nissan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nissanActionPerformed(evt);
            }
        });

        ren.setBackground(new java.awt.Color(255, 255, 255));
        ren.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ren.setForeground(new java.awt.Color(0, 0, 0));
        ren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_renault_30px.png"))); // NOI18N
        ren.setText("RENAULT");
        ren.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ren.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ren.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ren.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                renMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                renMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                renMouseReleased(evt);
            }
        });
        ren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renActionPerformed(evt);
            }
        });

        suz.setBackground(new java.awt.Color(255, 255, 255));
        suz.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        suz.setForeground(new java.awt.Color(0, 0, 0));
        suz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_honda_30px.png"))); // NOI18N
        suz.setText("HONDA");
        suz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suz.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        suz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suzMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                suzMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                suzMouseReleased(evt);
            }
        });
        suz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suzActionPerformed(evt);
            }
        });

        toy.setBackground(new java.awt.Color(255, 255, 255));
        toy.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        toy.setForeground(new java.awt.Color(0, 0, 0));
        toy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_toyota_30px.png"))); // NOI18N
        toy.setText("TOYOTA");
        toy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toy.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        toy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                toyMouseReleased(evt);
            }
        });
        toy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toyActionPerformed(evt);
            }
        });

        volk.setBackground(new java.awt.Color(255, 255, 255));
        volk.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        volk.setForeground(new java.awt.Color(0, 0, 0));
        volk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rent/icons8_volkswagen_30px.png"))); // NOI18N
        volk.setText("VOLKSWAGEN");
        volk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        volk.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        volk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        volk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volkMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                volkMouseReleased(evt);
            }
        });
        volk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nissan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hyn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(audi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(bmw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chevr, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(mazda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(ren, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suz, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fiat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(merc, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(toy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ford, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(audi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hyn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bmw, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chevr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fiat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ford, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mazda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(merc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mits, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nissan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ren, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(suz, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(volk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void audiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiActionPerformed
         String type="Audi";
    }//GEN-LAST:event_audiActionPerformed

    private void bmwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmwActionPerformed
        String type="BMW";
    }//GEN-LAST:event_bmwActionPerformed

    private void chevrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chevrActionPerformed
      String type="Chevrolet";
    }//GEN-LAST:event_chevrActionPerformed

    private void fiatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiatActionPerformed
         String type="FIAT";
    }//GEN-LAST:event_fiatActionPerformed

    private void fordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fordActionPerformed
         String type="Ford";
    }//GEN-LAST:event_fordActionPerformed

    private void audiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audiMouseClicked
        String type=audi.getText();
       
        frame.test(type);
        
        
        
        dispose();
    }//GEN-LAST:event_audiMouseClicked

    private void hynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hynActionPerformed
         String type="Hyundai";
    }//GEN-LAST:event_hynActionPerformed

    private void kiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiaActionPerformed
       String type="KIA";
    }//GEN-LAST:event_kiaActionPerformed

    private void mazdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mazdaActionPerformed
        String type="MAZDA";
    }//GEN-LAST:event_mazdaActionPerformed

    private void mercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercActionPerformed
        String type="Mercedes";
    }//GEN-LAST:event_mercActionPerformed

    private void mitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitsActionPerformed
       String type="Mitsubishi";
    }//GEN-LAST:event_mitsActionPerformed

    private void nissanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nissanActionPerformed
        String type="Nissan";
    }//GEN-LAST:event_nissanActionPerformed

    private void renActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renActionPerformed
     String type="RENAULT";
    }//GEN-LAST:event_renActionPerformed

    private void suzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suzActionPerformed
       String type="HONDA";
    }//GEN-LAST:event_suzActionPerformed

    private void toyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toyActionPerformed
        String type="Toyota";
    }//GEN-LAST:event_toyActionPerformed

    private void volkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volkActionPerformed
        String type="Volkswagen";
    }//GEN-LAST:event_volkActionPerformed

    private void bmwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmwMouseClicked
       String type=bmw.getText();
       
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_bmwMouseClicked

    private void chevrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chevrMouseClicked
      String type=chevr.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_chevrMouseClicked

    private void fiatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiatMouseClicked
         String type=fiat.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_fiatMouseClicked

    private void fordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fordMouseClicked
         String type=ford.getText();
        frame.test(type);
              dispose();
    }//GEN-LAST:event_fordMouseClicked

    private void hynMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hynMouseClicked
         String type=hyn.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_hynMouseClicked

    private void kiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiaMouseClicked
         String type=kia.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_kiaMouseClicked

    private void mazdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mazdaMouseClicked
         String type=mazda.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_mazdaMouseClicked

    private void mercMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mercMouseClicked
        String type=merc.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_mercMouseClicked

    private void mitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitsMouseClicked
         String type=mits.getText();
        frame.test(type);
              dispose();
    }//GEN-LAST:event_mitsMouseClicked

    private void nissanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nissanMouseClicked
         String type=nissan.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_nissanMouseClicked

    private void renMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renMouseClicked
         String type=ren.getText();
        frame.test(type);
             dispose();
    }//GEN-LAST:event_renMouseClicked

    private void suzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suzMouseClicked
        String type=suz.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_suzMouseClicked

    private void toyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toyMouseClicked
        String type=toy.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_toyMouseClicked

    private void volkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volkMouseClicked
        String type=volk.getText();
        frame.test(type);
       
        dispose();
    }//GEN-LAST:event_volkMouseClicked

    private void audiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audiMousePressed
    String type=audi.getText();
    frame1.testeur(type);  
    
    dispose();
    }//GEN-LAST:event_audiMousePressed

    private void bmwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmwMousePressed
      String type=bmw.getText();
    frame1.testeur(type); 
   
    dispose();
    }//GEN-LAST:event_bmwMousePressed

    private void chevrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chevrMousePressed
        String type=chevr.getText();
    frame1.testeur(type);  
   
    dispose();
    }//GEN-LAST:event_chevrMousePressed

    private void fiatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiatMousePressed
       String type=fiat.getText();
    frame1.testeur(type);  
    
    dispose();
    }//GEN-LAST:event_fiatMousePressed

    private void fordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fordMousePressed
       String type=ford.getText();
    frame1.testeur(type);  
   
    dispose();
    }//GEN-LAST:event_fordMousePressed

    private void hynMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hynMousePressed
        String type=hyn.getText();
    frame1.testeur(type);  
 
    dispose();
    }//GEN-LAST:event_hynMousePressed

    private void kiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiaMousePressed
      String type=kia.getText();
    frame1.testeur(type);
    
    dispose();
    }//GEN-LAST:event_kiaMousePressed

    private void mazdaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mazdaMousePressed
      String type=mazda.getText();
    frame1.testeur(type);  
   
    dispose();
    }//GEN-LAST:event_mazdaMousePressed

    private void mercMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mercMousePressed
       String type=merc.getText();
    frame1.testeur(type);  
   
    dispose();
         
    }//GEN-LAST:event_mercMousePressed

    private void mitsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitsMousePressed
          String type=mits.getText();
    frame1.testeur(type);  
    
    dispose();
    }//GEN-LAST:event_mitsMousePressed

    private void nissanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nissanMousePressed
          String type=nissan.getText();
    frame1.testeur(type);  
   
    dispose();
    }//GEN-LAST:event_nissanMousePressed

    private void renMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renMousePressed
        String type=ren.getText();
    frame1.testeur(type);  
    
    dispose();
    }//GEN-LAST:event_renMousePressed

    private void suzMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suzMousePressed
       String type=suz.getText();
    frame1.testeur(type);  
    
    dispose();
    }//GEN-LAST:event_suzMousePressed

    private void toyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toyMousePressed
       String type=toy.getText();
    frame1.testeur(type);  
    
    dispose();
    }//GEN-LAST:event_toyMousePressed

    private void volkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volkMousePressed
      String type=volk.getText();
    frame1.testeur(type);  
    
    dispose();
    }//GEN-LAST:event_volkMousePressed

    private void audiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audiMouseReleased
  String type=audi.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_audiMouseReleased

    private void bmwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmwMouseReleased
         String type=bmw.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_bmwMouseReleased

    private void chevrMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chevrMouseReleased
          String type=chevr.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_chevrMouseReleased

    private void fiatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiatMouseReleased
         String type=fiat.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_fiatMouseReleased

    private void fordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fordMouseReleased
         String type=ford.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_fordMouseReleased

    private void hynMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hynMouseReleased
          String type=hyn.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_hynMouseReleased

    private void kiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiaMouseReleased
          String type=kia.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_kiaMouseReleased

    private void mazdaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mazdaMouseReleased
         String type=mazda.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_mazdaMouseReleased

    private void mercMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mercMouseReleased
          String type=merc.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_mercMouseReleased

    private void mitsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mitsMouseReleased
          String type=mits.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_mitsMouseReleased

    private void nissanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nissanMouseReleased
          String type=nissan.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_nissanMouseReleased

    private void renMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renMouseReleased
         String type=ren.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_renMouseReleased

    private void suzMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suzMouseReleased
          String type=suz.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_suzMouseReleased

    private void toyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toyMouseReleased
          String type=toy.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_toyMouseReleased

    private void volkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volkMouseReleased
          String type=volk.getText();
      
    frame2.vt(type);
    dispose();
    }//GEN-LAST:event_volkMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new voiture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audi;
    private javax.swing.JButton bmw;
    private javax.swing.JButton chevr;
    private javax.swing.JButton fiat;
    private javax.swing.JButton ford;
    private javax.swing.JButton hyn;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton kia;
    private javax.swing.JButton mazda;
    private javax.swing.JButton merc;
    private javax.swing.JButton mits;
    private javax.swing.JButton nissan;
    private javax.swing.JButton ren;
    private javax.swing.JButton suz;
    private javax.swing.JButton toy;
    private javax.swing.JButton volk;
    // End of variables declaration//GEN-END:variables
}
